global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']  # Ensure this matches your service name and exposed port
